# Generated by Django 4.0.6 on 2022-09-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_influencer_block_influencer_image_shops_offers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shops',
            name='items',
        ),
        migrations.AddField(
            model_name='shops',
            name='items',
            field=models.ManyToManyField(to='app.item'),
        ),
    ]
