# Generated by Django 4.0.6 on 2022-09-30 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_brand_offer_remove_shops_items_item_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='influencer',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.influencer'),
        ),
    ]
