# Generated by Django 4.0.6 on 2022-10-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_offers_influencer_alter_offers_s_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='categorys',
            field=models.ManyToManyField(to='app.category'),
        ),
        migrations.AddField(
            model_name='offers',
            name='categorys',
            field=models.ManyToManyField(to='app.category'),
        ),
    ]
