# Generated by Django 4.0.6 on 2022-10-01 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_requests_accept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='influencer',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='s_item',
        ),
        migrations.CreateModel(
            name='item_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now=True)),
                ('influencer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.influencer')),
                ('s_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.item')),
            ],
        ),
    ]
