# Generated by Django 4.0.6 on 2022-10-01 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_offers_influencer_remove_offers_s_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_offer',
            name='influencer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.influencer'),
        ),
        migrations.AlterField(
            model_name='item_offer',
            name='s_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.item'),
        ),
    ]
