# Generated by Django 4.0.6 on 2022-10-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_item_offer_influencer_alter_item_offer_s_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_offer',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
