# Generated by Django 4.0.6 on 2022-10-05 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_item_offer_accept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(blank=True, null=True)),
                ('is_video', models.BooleanField()),
                ('comment_count', models.IntegerField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('media', models.FileField(upload_to='influncer_Posts/')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.influencer')),
            ],
        ),
    ]
