# Generated by Django 4.0.6 on 2022-10-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
