# Generated by Django 4.0.6 on 2022-10-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_influencer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
