# Generated by Django 4.0.6 on 2022-10-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
