# Generated by Django 4.0.6 on 2022-10-07 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
        ('app', '0021_alter_post_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('locathion', models.CharField(max_length=120)),
                ('quantity', models.IntegerField(default=1)),
                ('note', models.TextField()),
                ('copone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon')),
            ],
        ),
    ]
