# Generated by Django 4.0.6 on 2022-10-07 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.offers'),
        ),
    ]
