# Generated by Django 4.0.6 on 2022-10-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='total_price',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
