# Generated by Django 4.0.6 on 2022-10-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_checkout_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='xitem',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.item'),
        ),
    ]
