# Generated by Django 4.0.6 on 2022-10-10 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
        ('app', '0027_checkout_xitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='copone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon'),
        ),
    ]
