# Generated by Django 4.0.6 on 2022-10-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_checkout_xitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='post_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
