# Generated by Django 4.0.6 on 2022-10-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_influencer_post_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
