# Generated by Django 4.0.6 on 2022-10-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_post_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
