# Generated by Django 4.0.6 on 2022-10-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_mastertable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertable',
            name='time',
            field=models.DateTimeField(auto_now=True, unique=True),
        ),
    ]
