# Generated by Django 4.0.6 on 2022-10-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_mastertable_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertable',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
