# Generated by Django 4.0.6 on 2022-10-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_mastertable_acommunt_mastertable_alike_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastertable',
            name='communt_count',
        ),
        migrations.RemoveField(
            model_name='mastertable',
            name='likes',
        ),
    ]
