# Generated by Django 4.0.6 on 2022-10-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_mastertable_communt_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertable',
            name='er',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
