# Generated by Django 4.0.6 on 2022-10-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_checkout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_offer',
            name='admin_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requests',
            name='admin_accept',
            field=models.BooleanField(default=False),
        ),
    ]
