# Generated by Django 4.1.2 on 2022-11-07 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_influencer_engagemantrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='saveInfluncer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.brand')),
                ('infl', models.ManyToManyField(to='app.influencer')),
            ],
        ),
    ]
