# Generated by Django 4.1.3 on 2022-11-18 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_saveinfluncer'),
    ]

    operations = [
        migrations.CreateModel(
            name='influncerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.brand')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.influencer')),
            ],
        ),
    ]
