# Generated by Django 4.1.3 on 2022-11-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_influncerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='influncerrequest',
            name='adimnAccept',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influncerrequest',
            name='influncerAccept',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
